src/NDMotel/Controllers/AvailableRoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NDMotel.Models;
using System.Data.SqlClient;
using NDMotel.Data;
 

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace NDMotel.Controllers
{
    public class AvailableRoomsController : Controller
    {
        private readonly NDMotelContext _motelContext;
        
        
        public AvailableRoomsController(NDMotelContext context)
        {
            _motelContext = context;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            //Booking logic goes here
            return View();
        }

        
        public IActionResult AvailableRooms(string Location, DateTime BookingStartDate, DateTime BookingEndDate, int numOfPeople )
        {
            //PropertyID Prop = (PropertyID) Enum.Parse(typeof(PropertyID), Location);
            
            var numOfRoomsNeeded = (numOfPeople / 2);
            var roomTypes = _motelContext.RoomTypes;                   
            //var motelProperties = from mp in _motelContext.MotelProperties
            //                      where mp.Location == Location
            //                      select mp.ID;

           int locationID = _motelContext.MotelProperties.Where(p => p.Location == Location).Select(p => p.ID).FirstOrDefault();

           var TotalRoomInventory = _motelContext.RoomInventory.Where(p => p.MotelPropertiesID == locationID).Select(p=>p);
           
            //var roomReservation = from rr in _motelContext.RoomReservations
            //                      join mp in _motelContext.MotelProperties
            //                      on rr.MotelPropertiesID equals mp.ID
            //                      where rr.MotelPropertiesID == locationID && rr.checkIn < BookingEndDate && rr.checkOut > BookingStartDate
            //                      select rr;
            var existingRoomReservation = _motelContext.RoomReservations.Where(p => p.MotelPropertiesID == locationID && p.checkIn < (BookingEndDate) && p.checkOut > (BookingStartDate)).Select(p => p);
            List<ReturnAvailibility> availableRooms = new List<ReturnAvailibility>();

            foreach (RoomInventory rt in TotalRoomInventory)
            {
                int totalConsumption = 0;

                if (existingRoomReservation != null)
                { 
                 var existingBookedRoomofSpecificType = existingRoomReservation.Where(p => p.RoomTypeID == rt.RoomTypeID);
                 totalConsumption = existingRoomReservation.Count();
                }

                if (rt.NumberOfRooms >= totalConsumption)
                {
                    // Room of specific type is not available 
                    //NOTE: Logic is limited to check against requested reservations only and does note check existing reservations against each other
                    //for validation of availibility
                    var description = roomTypes.Where(p => p.ID == rt.RoomTypeID).Select(p => p.RoomDescription).First();
                    var roomName = roomTypes.Where(p => p.ID == rt.RoomTypeID).Select(p => p.RoomName).First();

                    availableRooms.Add(new ReturnAvailibility {
                                                    Description = description,
                                                     //HighestPrice = rt.HighestPrice,
                                                     LowestPrice = rt.BestPrice,
                                                     Name = roomName
                                                    });  
                }
                
            }
            //List<BookRoom> BookRoom = new List<BookRoom>();
            BookRoom roomdetail = new BookRoom {
                RoomDetail = availableRooms,
                checkinDate = ( BookingStartDate),
                checkoutDate = (BookingEndDate),
                noofpeope = numOfPeople,
                locationid = locationID
               };

            //BookRoom.Add(roomdetail);

            return View(roomdetail);
            
        }
    }
}

src/NDMotel/Controllers/BookRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NDMotel.Models;
using NDMotel.Data;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace NDMotel.Controllers
{
    public class BookRoomController : Controller
    {

        private readonly NDMotelContext _motelContext;


        public BookRoomController(NDMotelContext context)
        {
            _motelContext = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(BookRoom confirmBooking, String btnbookroom)
        {
            var roomName = _motelContext.RoomTypes.Where(p => p.RoomName == btnbookroom).Select(p=>p.RoomName).FirstOrDefault();
            var roomTypeID = _motelContext.RoomTypes.Where(p => p.RoomName == roomName).Select(x => x.ID).FirstOrDefault();
            var guestID = _motelContext.Guests.Where(p => p.FirstName == confirmBooking.firstName && p.LastName == confirmBooking.lastName).Select(x => x.ID).FirstOrDefault();
            var locationID = 1;
            Guest g = new Guest() { 
                FirstName = confirmBooking.firstName,
                LastName = confirmBooking.lastName,
                Address = confirmBooking.address,
                PhoneNumber = confirmBooking.phoneno,
                ZipCode = confirmBooking.zipcode
            } ;
           
            RoomReservation confirmRoomReservation = new RoomReservation()
            {
                RoomTypeID = roomTypeID,
                GuestID = g.ID,
                checkIn = confirmBooking.checkinDate,
                checkOut = confirmBooking.checkoutDate,
                MotelPropertiesID = locationID
            };
            confirmRoomReservation.Guest = g;
            _motelContext.RoomReservations.Add(confirmRoomReservation);


            //_motelContext.Entry(confirmRoomReservation).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _motelContext.SaveChanges();

            ViewData["ReservationID"] = confirmRoomReservation.ID;
            
            return View(confirmRoomReservation);
        }
    }
}
       


src/NDMotel/Views/AvailableRooms/AvailableRooms.cshtml
@model  NDMotel.Models.BookRoom

@{
    ViewData["Title"] = "Available Rooms";
}

<h3>Note: </h3>
<h2 class="alert">Please enter your personal details below before clicking the book button! Thank you for your business.</h2>

@using (Html.BeginForm("Index", "BookRoom", FormMethod.Post))
{
    @Html.ValidationSummary()

    <tr>
        <b>Selected Check-In Date:</b> <td class="text-primary">@Html.DisplayFor(model => model.checkinDate)</td>
        @Html.HiddenFor(model=>model.checkinDate)
        <b>Selected Check-Out Date:</b> <td>@Html.DisplayFor(model => model.checkoutDate)</td>
        @Html.HiddenFor(model => model.checkoutDate)
        <b>Selected Number of Guests:</b> <td>@Html.DisplayFor(model => model.noofpeope)</td>
        @Html.HiddenFor(model => model.noofpeope)
        
</tr>
    <br />
    <table class="table">
            
    <thead>
        <tr>
            <th colspan="4">
                @Html.DisplayNameFor(model => model.RoomDetail[0].Name)
            </th>
            <th colspan="4">
                @Html.DisplayNameFor(model => model.RoomDetail[0].Description)
            </th>
            <th colspan="4">
                @Html.DisplayNameFor(model => model.RoomDetail[0].LowestPrice)
            </th>
            <th colspan="4"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.RoomDetail)
        {
            <tr>
            <td colspan="4">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td colspan="4">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td colspan="4">
                @Html.DisplayFor(modelItem => item.LowestPrice)
            </td>
            <td colspan="4">
                    
                <input type="submit" value="@item.Name" class="btn-primary" name="btnbookroom" />
            </td>
            </tr>
        }
    </tbody>

    </table>

     <div>
         <div>
             <label>Please Enter your First Name:</label><br />
             @Html.EditorFor(model => model.firstName)<br />
             @Html.ValidationMessageFor(model => model.firstName)
         </div>
         <div>
             <label>Please Enter your Last Name:</label><br />
              @Html.EditorFor(model => model.lastName)<br />
              @Html.ValidationMessageFor(model => model.lastName)
         </div>
         <div>
             <label>Please Enter your Full Address:</label><br />
             @Html.EditorFor(model => model.address)<br />
             @Html.ValidationMessageFor(model => model.address)
         </div>
         <div>
             <label>Please Enter your ZipCode:</label><br />
             @Html.EditorFor(model => model.zipcode)<br />
             @Html.ValidationMessageFor(model => model.zipcode)
         </div>
         <div>
             <label>Please Enter your Phone No:</label><br />
             @Html.EditorFor(model => model.phoneno)<br />
             @Html.ValidationMessageFor(model => model.phoneno)
         </div>
       </div>

}

src/NDMotel/Views/AvailableRooms/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <h2> Your booking was confired.</h2>
}